### ISSUE TITLE
能把版权那一行去掉吗？太丑

### ISSUE THREAD

**Issue by finalion** [aleen42/gitbook-treeview#3]
能把版权那一行去掉吗？太丑

**Comment by aleen42** [comment]
@finalion copyright 傳空字符串即可. 具體可看 Issue #2 的建議.

**Comment by finalion** [comment]
@aleen42 no effects, please check it again.

**Comment by aleen42** [comment]
@finalion I have fixed this problem in the latest version **2.7.2**, and check whether it's worked for you. Remember that, recently Gitbook has used a cache strategy to improve loading performance of sites. If you want to clear cache, you may fresh the site again.

**Comment by finalion** [comment]
@aleen42 sorry, it still doesn't work. When I pass the empty strings to copyright, it shows the default value.

**Comment by aleen42** [comment]
@finalion Here is some advise:
1. Firstly, check whether you're using the version 2.7.2 to build your book
2. If so, then check if you're passing right, or you can setup a configuration as followed:

``` json
"page-treeview": {
    "copyright": "",
    "style": "markdown",
    "minHeaderCount": "2",
    "minHeaderDeep": "2"
},
```
1. When you rebuild your book, you may have to refresh several times to clear cache of Gitbook

**Comment by finalion** [comment]
@aleen42 now it works, thank you for your great work. Have you thought about showing the leftside summary structures with tree-view?

**Comment by aleen42** [comment]
@finalion If you like it, please star my project for supports. Actually, when it comes to he summary structures in the left-side bar, it's a structure of tree itself, and I don't think I would take this into my tree-view, as my plugin mainly aims to analyse the structure of our single page. Certainly, if you have some good ideas, it's welcome to share with me, or directly fork and give out a pull request for you idea.

**Comment by finalion** [comment]
@aleen42 You know, the left-side bar is build in Summary.md which needs manual edit, and it neither does not support section navigation for one page. I have not focused on gitbook plugins development and do not know if this could be automatically implemented by a plugin.

**Comment by aleen42** [comment]
@finalion `Summary.md` is needed by Gitbook to build books, and when it comes to using a plugin to generate automatically for you, I don't think it can. Certainly, you can create a script with nodejs to run locally, which aims to search for all files in the book, and generate the `Summary.md` file for you.

**Comment by finalion** [comment]
I know, but sections structure in single .md file are impossible to add to. So, maybe, is summary.html needed to be modified?

**Comment by finalion** [comment]
You can closed this issue now.

**Comment by finalion** [comment]
This issue can be closed now.

**Comment by aleen42** [comment]
@finalion https://github.com/GitbookIO/gitbook-convert, check this project.
